engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"

ratings:
  paths:
  - "src/find_substrings/**.py"
  - "tests/**.py"
