dist: xenial
language: python

python:
  - '3.8'
#  - '3.6'

install:
  #- pip install -e .
  - pip install -r requirements.txt
  - python setup.py install 
  
script:
  - black --check src/
  - black --check tests/
  - pytest --cov=src -v -rs 
  
after_success:
  — coveralls
