OS: 
  - linux
  - windows
  - OSX
  
dist: 
  - xenial

language: python

python:
  - '3.8'
  - 'pypy3'
  - 'nightly'
  
matrix:
  include:
    - python: 3.3 #Travis doesn't include a Py3.3 dist for xenial on Ubuntu
      dist: trusty


install:
  - pip install -U pip
  - pip install tox-travis
  - pip install -r requirements-dev.txt #dependencies for pytest, code coverage, and formatting
#  - python setup.py install  #instead of the usual - pip install -e . (which tells Travis to install my package as a wheel)
                             #- pip install -r requirements.txt #this is covered by setup.py
  
script:
  - tox
 # - black --check src/
#  - black --check tests/
 # - pytest --cov=src -v -rs 
  
after_success:
  — coveralls
