dist: xenial
language: python

python:
  - '3.8'
#  - '3.6'

install:
  - python setup.py install  #instead of the usual - pip install -e . (which tells Travis to install my package as a wheel)
                             #- pip install -r requirements.txt #this should already be covered by setup.py
  
script:
  - black --check src/
  - black --check tests/
  - pytest --cov=src -v -rs 
  
after_success:
  — coveralls
