dist: xenial
language: python

python:
  - '3.8'
#  - '3.6'

install:
  - pip install -r requirements.txt
  - python setup.py install #could also have Travis install our package like this: pip install -e .
  
script:
  - black --check src/
  - black --check tests/
  - pytest -v -rs
