language: python

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 
        - 3.8
        - pypy3
        - nightly
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # install Python through shell since 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # manually installing Python since 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

python:
  - '3.8'
  - 'pypy3'
  - 'nightly'
  
matrix:
  include:
    - python: 3.3 #Travis doesn't include a Py33 dist for xenial on Ubuntu
      dist: trusty


install:
  - pip install -U pip
  - pip install tox-travis
#  - pip install -r requirements-dev.txt --> dependencies for pytest, code coverage, and formatting --> already being handled by tox
#  - python setup.py install  --> we use setup.py instead of the usual - pip install -e . (which tells Travis to install my package as a wheel)
#  - pip install -r requirements.txt --> this is covered by setup.py
  
script:
  - tox
 # - black --check src/
#  - black --check tests/
 # - pytest --cov=src -v -rs 
  
after_success:
  — coveralls
